- hosts: "{{local}}"
  vars_files:
      - group_vars/dev_env_servers
      - host_vars/localhost
  tasks:
  - name: List Packages to Uninstall
    debug:
      msg: "{{ item }}"
    with_items: "{{ brew_packages }}"

  - name: Uninstall Packages
    homebrew:
      name: "{{ brew_packages }}"
      state: absent
  - name: List Cask Packages to Uninstall
    debug:
      msg: "{{ item }}"
    with_items: "{{ brew_cask_packages }}"

  - name: Uninstall Cask Packages
    homebrew:
      name: "{{ brew_cask_packages }}"
      state: absent
