- hosts: "{{local}}"
  vars_files:
      - group_vars/dev_env_servers
      - host_vars/localhost
  tasks:
  - name: List Packages to Install
    debug:
      msg: "{{ item }}"
    with_items: "{{ brew_packages }}"

  - name: Install Packages
    homebrew:
      name: "{{ brew_packages }}"
      state: latest

  - name: List Cask Packages to Install
    debug:
      msg: "{{ item }}"
    with_items: "{{ brew_cask_packages }}"

  - name: Install Cask Packages
    homebrew_cask:
      name: "{{ brew_cask_packages }}"
      state: latest
